# Generated by Django 4.2.1 on 2023-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pic/avatar.png/', upload_to='profile_pic/'),
        ),
    ]
