# Generated by Django 4.2 on 2023-04-17 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 17, 23, 36, 40, 491322, tzinfo=datetime.timezone.utc)),
        ),
    ]
