# Generated by Django 4.2 on 2023-04-18 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 10, 14, 7, 789837, tzinfo=datetime.timezone.utc)),
        ),
    ]
