# Generated by Django 4.2 on 2023-04-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_picture_alter_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
