# Generated by Django 4.2 on 2023-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_profile_profile_pic_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pic/avatar.png', upload_to='profile_pic/'),
        ),
    ]
