# Generated by Django 4.2 on 2023-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_status_post_blog_post_date_55752c_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['timestamp'], name='blog_commen_timesta_90baf8_idx'),
        ),
    ]
